### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by EL-Nazer** [amitshree/magento2-marketplace#1]
Problem 1
    - Installation request for amitshree-marketplace dev-master -> satisfiable by amitshree-marketplace[dev-master].
    - amitshree-marketplace dev-master requires magento/framework 100.2.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by EL-Nazer** [comment]
After Changing minimum-stability ti dev from Composer.json / found the following

Magneto 2.2.1 

Problem 1
    - Can only install one of: magento/framework[100.2.0-rc20, 101.0.1].
    - Can only install one of: magento/framework[101.0.1, 100.2.0-rc20].
    - Can only install one of: magento/framework[101.0.1, 100.2.0-rc20].
    - amitshree-marketplace dev-master requires magento/framework 100.2.* -> satisfiable by magento/framework[100.2.0-rc20].
    - Installation request for amitshree-marketplace dev-master -> satisfiable by amitshree-marketplace[dev-master].
    - Installation request for magento/framework (locked at 101.0.1) -> satisfiable by magento/framework[101.0.1].

**Comment by amitshree** [comment]
I have updated the require section.
